build: use common Hedera Gradle config
hashgraph/hedera-block-node pull request #216
Opened 2024-09-26 23:44 UTC by jjohannes

**Description**:
⚠️ WiP - works when the config is provided locally, but it yet needs to be publish 

**Related issue(s)**:

https://github.com/hashgraph/hedera-services/issues/14255

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-16 15:41 UTC, jsync-swirlds commented on buildSrc/build.gradle.kts
With all of these files moved to a single shared conventions plugin, what options exist to modify that behavior for different projects (e.g. this project may not retain identical java version settings to hedera-services indefinitely).

2024-11-15 07:09 UTC, jjohannes commented on buildSrc/build.gradle.kts
Goal is to move everything that's to be controlled by projects - like the Java version – out of the Gradle convention plugins into separate configuration files.
The Java version will be located here after this change:  [gradle/jdk-version.txt](https://github.com/hashgraph/hedera-block-node/blob/14255-reusable-gradle-config/gradle/jdk-version.txt)

I am fairly confident that we already have a good compromise between what we want to share purposefully to have a alignment between projects and what projects still should/need to control individually. But we will observer this closely after this change and do adjustments as needed.

2024-12-11 14:42 UTC, jjohannes commented on .github/dependabot.yml
> +      interval: weekly
With having all versions in the standard format in `hiero-dependency-versions`, Dependbot will start working on this Repo for Gradle-managed dependencies as it does on others repos.

2024-12-11 15:02 UTC, jjohannes commented on .github/workflows/pr-checks.yaml
> +        run: ${GRADLE_EXEC} assemble --scan
`build` did everything already and the two other steps below were obsolete.

The split-up in three steps is what we also do in other repos:

- assemple (everything compiles)
- qualityCheck (all checks: spotless, dependency scopes)
- check (run tests)

2024-12-12 08:14 UTC, mishomihov00 submitted a review, later dismissed
Review applies to `.github/dependabot.yml` and `.github/workflows/pr-checks.yaml`

2024-12-18 20:36 UTC, rbarkerSL requested changes
Just one question. Prefer to avoid storing binaries if we can avoid it.

2024-12-18 20:36 UTC, rbarkerSL commented on gradle/wrapper/gradle-wrapper.jar
Should this jar be present? I thought that gradle would pick this up natively. Maybe a miss in the .gitignore?

2024-12-18 21:05 UTC, jsync-swirlds commented on gradle/wrapper/gradle-wrapper.jar
Gradle recommends storing the wrapper jar in the code repo.
The same jar is present in our other gradle managed repos (e.g. services [here](https://github.com/hashgraph/hedera-services/tree/develop/gradle/wrapper)).

2024-12-18 21:22 UTC, jjohannes commented on gradle/wrapper/gradle-wrapper.jar
Yes that's correct. This Jar contains the "Wrapper Tool" that downloads Gradle itself in the correct version so you do not need to install it manually. And yes, it would be somehow better if it would not be a binary, but it's the only solution available.

On the upside, the Gradle GH action we use validates that this file is the official one. So if if someone would attempt to sneak in a compromised Jar disguised as a Gradle update, the action would detect it.

The Jar typically does not need to be updated. But sometimes there are new features in the Wrapper itself after a Gradle update. Then, when you changed the Gradle version, you can run `./gradlew wrapper` and the Jar is update if a new version exists (which was the case here).

2024-12-19 17:25 UTC, mattp-swirldslabs reviewed
Hi Jendrik, I need to merge in our implementation of the deterministic build and deterministic images before you merge this PR. Is that ok?

2024-12-19 18:26 UTC, jjohannes commented
@mattp-swirldslabs sure go ahead.
I am taking some days off for the holidays. I won't get back to this before January anyway.
I will deal with potential conflicts then if there are any.

2024-12-28 01:58 UTC, AlfredoG87 approved these changes
LGTM, however needs conflict resolution due to parallel efforts to make the build deterministic.

2025-01-02 15:53 UTC, rbarkerSL commented on stream/build.gradle.kts
> +        tag = "1033f10"
Assuming this is for testing prior to merge? Will we be back on main when we do merge?

2025-01-02 15:59 UTC, rbarkerSL submitted a review, later dismissed
Looks okay.

2025-01-09 08:41 UTC, jjohannes commented on stream/build.gradle.kts
> +        tag = "1033f10"
This is the same as on main. The code is only slightly reformatted as the complete task setup is now done here instead of inside a custom plugin. The only real change is replacing `tasks.cloneHederaProtobufs` with  `tasks.register<GitClone>("cloneHederaProtobufs")`.

2025-01-09 11:48 UTC, ata-nas reviewed
@jjohannes LG. A couple of nits/questions.

Just recently, a migration to SPDX license headers happened. Maybe some headers were missed, I am unsure which or if all files are eligible to have this header. Please feel free to proactively resolve my comments if files, where I have left a comment for the header, should not actually have the header. (My comments are mostly to bring attention in case some headers might be missed)

2025-01-09 11:48 UTC, ata-nas commented on .github/dependabot.yml
> +      interval: weekly
File does not end with an newline char.

2025-01-09 11:48 UTC, ata-nas commented on .github/dependabot.yml
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on gradle.properties
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on gradle/toolchain-versions.properties
> +jdk=21.0.4
Shouldn't this jdk version be `21.0.5`?

2025-01-09 11:48 UTC, ata-nas commented on gradle/toolchain-versions.properties
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on gradle/wrapper/gradle-wrapper.properties
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on server/src/main/java/module-info.java
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on simulator/src/main/java/module-info.java
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on stream/src/main/java/module-info.java
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on suites/build.gradle.kts
> +}
Why was this added here?

2025-01-09 11:48 UTC, ata-nas commented on suites/src/main/java/module-info.java
Should this file also have the SPDX license header?

2025-01-09 11:48 UTC, ata-nas commented on version.txt
Should this file also have the SPDX license header?

2025-01-09 12:13 UTC, jjohannes commented on gradle.properties
In my opinion we do not need that for properties files.

But if, it should also be automated through `spotlessApply`. In this PR, I would prefer to not add it. But we can do it in a follow up, if it is desired.

2025-01-09 12:16 UTC, jjohannes commented on gradle/toolchain-versions.properties
> +jdk=21.0.4
This is moved from here: https://github.com/hashgraph/hedera-block-node/blob/main/buildSrc/src/main/kotlin/com.hedera.block.conventions.gradle.kts#L20

Updating to Java `21.0.5` should be done in a follow up:  https://github.com/hashgraph/hedera-block-node/issues/453

2025-01-09 12:16 UTC, jjohannes commented on gradle/toolchain-versions.properties
See my comment on `gradle.properties`.

2025-01-09 12:17 UTC, jjohannes commented on gradle/wrapper/gradle-wrapper.properties
No. This file is generated autoamtically by Gradle.

2025-01-09 12:18 UTC, jjohannes commented on version.txt
No. This is only a number and comments are not allowed in this file. (The code we have that parses and automatically updates the file does not support comments atm.)

2025-01-09 12:21 UTC, jjohannes commented on suites/build.gradle.kts
> +}
Good catch! This is a mistake. I don't know how this happened. Will remove.

2025-01-09 12:29 UTC, jjohannes commented
Thanks @ata-nas. Addressed the comments and/or answered. Note that the headers I added manually now will also be handled by `spotlessApply` in the near future. Related:

- https://github.com/hiero-ledger/hiero-gradle-conventions/issues/22
- https://github.com/hiero-ledger/hiero-gradle-conventions/issues/30#issuecomment-2580033004

2025-01-09 12:33 UTC, ata-nas commented on gradle.properties
@AlfredoG87 @mattp-swirldslabs @georgi-l95 @jsync-swirlds @jasperpotts tag for awareness about the headers. I will resolve this comment from my side.

2025-01-09 12:37 UTC, ata-nas approved these changes
@jjohannes looks good! Before merging please see also if others have other comments (I remember people asked in the near past to wait with merging this for a bit, since they needed to change things which would conflict with this, I am not sure if everybody is ready) @AlfredoG87 @mattp-swirldslabs @jsync-swirlds @georgi-l95 @jasperpotts tag for awareness.

2025-01-09 15:33 UTC, jsync-swirlds commented on gradlew
> +#
This is not our code to relicense, I don't think...
It's also duplicative with the block immediately prior.

2025-01-09 15:33 UTC, jsync-swirlds commented on gradlew.bat
> +@rem
Same here, adding SPDX to gradle-owned code.

2025-01-09 16:11 UTC, jjohannes commented on gradlew
> +#
This is not our doing. It is done by Gradle itself. It was recently added: https://github.com/gradle/gradle/pull/28801

It's in this PR because I did a full upgrade by running `./gradlew wrapper` with the latest versions.

2025-01-09 16:11 UTC, jjohannes commented on gradlew.bat
> +@rem
Same as with `gradlew` script

2025-01-09 16:45 UTC, jsync-swirlds commented on gradlew
> +#
Ahh, I assumed it was our change.
If gradle is making the change, then that's fine.

2025-01-09 17:02 UTC, andrewb1269hg approved these changes
Review and approve following files:
`.github/dependabot.yml`
`.github/workflows/pr-checks.yaml`

2025-01-09 18:06 UTC, merged