Adding network latency simulator for block live stream consumers
hashgraph/hedera-block-node pull request #34
Opened 2024-06-29 00:19 UTC by AlfredoG87

**Description**:
Adding network latency simulator for block live stream consumers

The result of the Test was successful:
- The Server was not blocked by slow consumers, 
- The consumers were able to consume blocks as fast as their networks allowed them,
- The control consumer that did not had any restrictions was not impacted by the network issues of other consumers. 
- And more importantly, once the network issues (latency) resolved on the simulated consumers, the messages or blocks arrived in the correct order

**Related issue(s)**:

Fixes #32 

**Notes for reviewer**:
Due to how Dockerfile performs COPY I had to create a copy of the files `consumer.sh` and `protobuf` foldere inside the test project. But I would welcome a suggestion on how to copy relative paths that are above the folder structure of the main project of Dockerfile when building the image.

How is working:
![image](https://github.com/hashgraph/hedera-block-node/assets/123040664/e434622d-bf44-401a-bf1e-649c926e72ab)

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-01 21:59 UTC, mattp-swirldslabs requested changes
Looks pretty good.  I added a few suggestions

2024-07-02 16:35 UTC, AlfredoG87 commented on server/src/test/network-latency-simulator/consumer.sh
> +#!/bin/bash
✅ Done

2024-07-02 16:35 UTC, AlfredoG87 commented on server/src/test/network-latency-simulator/Dockerfile
> +RUN chmod +x /usr/local/bin/configure_latency.sh /usr/local/bin/consumer.sh /usr/local/bin/start.sh
✅  Done

2024-07-02 16:35 UTC, AlfredoG87 commented on server/src/test/network-latency-simulator/README.md
> +docker run -it --cap-add=NET_ADMIN latency-simulator
✅  Done!

2024-07-02 16:35 UTC, AlfredoG87 commented on server/src/test/network-latency-simulator/README.md
> +docker run -it --cap-add=NET_ADMIN -e LATENCY_INCREASE_INTERVAL=5 -e INITIAL_LATENCY=1000 -e JITTER=1000 -e BANDWIDTH=128 -e INCREASE_TIME=5 -e MAX_LATENCY=10000
✅  Done

2024-07-02 16:35 UTC, AlfredoG87 commented on server/src/test/network-latency-simulator/protos/blockstream.proto
> +syntax = "proto3";
✅  Done

2024-07-02 16:59 UTC, mattp-swirldslabs approved these changes
Looks good!

2024-07-03 15:51 UTC, merged