00029 refactor demo disruptor
hashgraph/hedera-block-node pull request #41
Opened 2024-07-09 21:07 UTC by mattp-swirldslabs

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-08-06 19:12 UTC, AlfredoG87 requested changes
LGTM, only thing that I would add is a Diagram on the design doc, so is easier to understand the ring buffer and the interactions between the classes.

Leaved some nits.

2024-08-07 15:40 UTC, mattp-swirldslabs commented on server/src/main/java/com/hedera/block/server/BlockStreamService.java
> +                            System.Logger.Level.INFO,
Good point, I forgot to change this back after building the feature out.  I've been using DEBUG for most of these. Do you mind if I use DEBUG here as well?

2024-08-07 16:07 UTC, mattp-swirldslabs commented on server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
> +        Thread.sleep(51);
Good catch! I forgot to remove that when I converted to using a InstantSource mock

2024-08-07 16:08 UTC, mattp-swirldslabs commented on server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
> +            LOGGER.log(System.Logger.Level.INFO, "Publishing BlockItem: {0}", blockItem);
Good catch. I forgot to change this back to DEBUG after troubleshooting. Fixed

2024-08-07 16:10 UTC, mattp-swirldslabs commented on server/src/main/java/com/hedera/block/server/BlockStreamService.java
> +    // TODO: Fix this error type once we have it - should not be success
Fixed.

2024-08-07 16:45 UTC, mattp-swirldslabs commented on server/src/main/java/com/hedera/block/server/ServiceStatusImpl.java
> +        webServer.stop();
I added some additional comments. The order matters. We don't want to accept new connections before the server shuts down. This flag also triggers running connections to respond with appropriate, spec-related protobuf responses.

2024-08-07 17:38 UTC, AlfredoG87 commented on server/src/main/java/com/hedera/block/server/BlockStreamService.java
> +                            System.Logger.Level.DEBUG, "Block number {0} not found", blockNumber);
Yes I agree that either DEBUG or TRACE are appropiate, but yes, I think consistency is better, so lets use DEBUG 👍

2024-08-07 17:39 UTC, AlfredoG87 commented on server/docs/design/block-persistence.md
> +### Design
I forgot we already have a design document for this, nvm...

2024-08-12 15:16 UTC, AlfredoG87 approved these changes

2024-08-12 15:17 UTC, AlfredoG87 submitted a review, later dismissed
LGTM

2024-08-12 15:47 UTC, AlfredoG87 approved these changes
LGTM

2024-08-12 15:48 UTC, merged